CREATE DATABASE IF NOT EXISTS `testsite` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE testsite;

CREATE TABLE IF NOT EXISTS  `users` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 100 ) NOT NULL ,
`email` VARCHAR( 100 ) NOT NULL ,
`password` VARCHAR( 100 ) NOT NULL) ENGINE = INNODB;